SHARED_PATH=../../mission_server/

all:
	g++ -g -o test_no_ms_1 test_no_ms_1.cpp $(SHARED_PATH)mission_server.cpp -I$(SHARED_PATH) -lproc
	g++ -g -o test_no_ms_2 test_no_ms_2.cpp $(SHARED_PATH)mission_server.cpp -I$(SHARED_PATH) -lproc
